"use strict";Object.defineProperty(exports,"__esModule",{value:!0});var t=require("@aboutyou/backbone"),e=function(){return(e=Object.assign||function(t){for(var e,r=1,o=arguments.length;r<o;r++)for(var n in e=arguments[r])Object.prototype.hasOwnProperty.call(e,n)&&(t[n]=e[n]);return t}).apply(this,arguments)};
/*! *****************************************************************************
Copyright (c) Microsoft Corporation. All rights reserved.
Licensed under the Apache License, Version 2.0 (the "License"); you may not use
this file except in compliance with the License. You may obtain a copy of the
License at http://www.apache.org/licenses/LICENSE-2.0

THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE,
MERCHANTABLITY OR NON-INFRINGEMENT.

See the Apache Version 2.0 License for specific language governing permissions
and limitations under the License.
***************************************************************************** */function r(t,e){var r,o,n,a,i={label:0,sent:function(){if(1&n[0])throw n[1];return n[1]},trys:[],ops:[]};return a={next:u(0),throw:u(1),return:u(2)},"function"==typeof Symbol&&(a[Symbol.iterator]=function(){return this}),a;function u(a){return function(u){return function(a){if(r)throw new TypeError("Generator is already executing.");for(;i;)try{if(r=1,o&&(n=2&a[0]?o.return:a[0]?o.throw||((n=o.return)&&n.call(o),0):o.next)&&!(n=n.call(o,a[1])).done)return n;switch(o=0,n&&(a=[2&a[0],n.value]),a[0]){case 0:case 1:n=a;break;case 4:return i.label++,{value:a[1],done:!1};case 5:i.label++,o=a[1],a=[0];continue;case 7:a=i.ops.pop(),i.trys.pop();continue;default:if(!(n=(n=i.trys).length>0&&n[n.length-1])&&(6===a[0]||2===a[0])){i=0;continue}if(3===a[0]&&(!n||a[1]>n[0]&&a[1]<n[3])){i.label=a[1];break}if(6===a[0]&&i.label<n[1]){i.label=n[1],n=a;break}if(n&&i.label<n[2]){i.label=n[2],i.ops.push(a);break}n[2]&&i.ops.pop(),i.trys.pop();continue}a=e.call(t,i)}catch(t){a=[6,t],o=0}finally{r=n=0}if(5&a[0])throw a[1];return{value:a[0]?a[1]:void 0,done:!0}}([a,u])}}}exports.api=null;var o={getProductApi:function(){},getCategoryApi:function(t){return e=this,o=void 0,a=function(){return r(this,(function(e){switch(e.label){case 0:return t||(this.options={}),t.ids?[4,exports.api.categories.getByIds(t.ids,{with:t.with})]:[3,2];case 1:return[2,e.sent()];case 2:return t.path?[2,exports.api.ctagories.getByPath(t.path,{width:t.with})]:[3,3];case 3:return[4,exports.api.categories.getRoots({with:t.with})];case 4:return[2,e.sent()]}}))},new((n=void 0)||(n=Promise))((function(t,r){function i(t){try{p(a.next(t))}catch(t){r(t)}}function u(t){try{p(a.throw(t))}catch(t){r(t)}}function p(e){e.done?t(e.value):new n((function(t){t(e.value)})).then(i,u)}p((a=a.apply(e,o||[])).next())}));var e,o,n,a},addToCartApi:function(){},removeFromCartApi:function(){},clearCartApi:function(){},placeOrderApi:function(){},getUserApi:function(){},addCouponApi:function(){},removeCouponApi:function(){}};var n=o.getProductApi,a=o.getCategoryApi,i=o.addToCartApi,u=o.removeFromCartApi,p=o.clearCartApi,c=o.placeOrderApi,s=o.getUserApi,l=o.addCouponApi,f=o.removeCouponApi;exports.addCoupon=l,exports.addToCart=i,exports.clearCart=p,exports.getCategory=a,exports.getProduct=n,exports.getUser=s,exports.override=function(t){o=e(e({},o),t)},exports.placeOrder=c,exports.removeCoupon=f,exports.removeFromCart=u,exports.setup=function(){exports.api=new t.BapiClient({host:"http://boston.backbone-api.demo.aboutyou.cloud/v1/",auth:{username:"aboutyou",password:"OmNErAb96Y5Qn75SFhXr"},shopId:121})};
