import{BapiClient as t}from"@aboutyou/backbone";
/*! *****************************************************************************
Copyright (c) Microsoft Corporation. All rights reserved.
Licensed under the Apache License, Version 2.0 (the "License"); you may not use
this file except in compliance with the License. You may obtain a copy of the
License at http://www.apache.org/licenses/LICENSE-2.0

THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE,
MERCHANTABLITY OR NON-INFRINGEMENT.

See the Apache Version 2.0 License for specific language governing permissions
and limitations under the License.
***************************************************************************** */var e=function(){return(e=Object.assign||function(t){for(var e,n=1,r=arguments.length;n<r;n++)for(var o in e=arguments[n])Object.prototype.hasOwnProperty.call(e,o)&&(t[o]=e[o]);return t}).apply(this,arguments)};function n(t,e){var n,r,o,i,a={label:0,sent:function(){if(1&o[0])throw o[1];return o[1]},trys:[],ops:[]};return i={next:u(0),throw:u(1),return:u(2)},"function"==typeof Symbol&&(i[Symbol.iterator]=function(){return this}),i;function u(i){return function(u){return function(i){if(n)throw new TypeError("Generator is already executing.");for(;a;)try{if(n=1,r&&(o=2&i[0]?r.return:i[0]?r.throw||((o=r.return)&&o.call(r),0):r.next)&&!(o=o.call(r,i[1])).done)return o;switch(r=0,o&&(i=[2&i[0],o.value]),i[0]){case 0:case 1:o=i;break;case 4:return a.label++,{value:i[1],done:!1};case 5:a.label++,r=i[1],i=[0];continue;case 7:i=a.ops.pop(),a.trys.pop();continue;default:if(!(o=(o=a.trys).length>0&&o[o.length-1])&&(6===i[0]||2===i[0])){a=0;continue}if(3===i[0]&&(!o||i[1]>o[0]&&i[1]<o[3])){a.label=i[1];break}if(6===i[0]&&a.label<o[1]){a.label=o[1],o=i;break}if(o&&a.label<o[2]){a.label=o[2],a.ops.push(i);break}o[2]&&a.ops.pop(),a.trys.pop();continue}i=e.call(t,a)}catch(t){i=[6,t],r=0}finally{n=o=0}if(5&i[0])throw i[1];return{value:i[0]?i[1]:void 0,done:!0}}([i,u])}}}var r=null,o={getProductApi:function(){},getCategoryApi:function(t){return e=this,o=void 0,a=function(){return n(this,(function(e){switch(e.label){case 0:return t||(this.options={}),t.ids?[4,r.categories.getByIds(t.ids,{with:t.with})]:[3,2];case 1:return[2,e.sent()];case 2:return t.path?[2,r.ctagories.getByPath(t.path,{width:t.with})]:[3,3];case 3:return[4,r.categories.getRoots({with:t.with})];case 4:return[2,e.sent()]}}))},new((i=void 0)||(i=Promise))((function(t,n){function r(t){try{c(a.next(t))}catch(t){n(t)}}function u(t){try{c(a.throw(t))}catch(t){n(t)}}function c(e){e.done?t(e.value):new i((function(t){t(e.value)})).then(r,u)}c((a=a.apply(e,o||[])).next())}));var e,o,i,a},addToCartApi:function(){},removeFromCartApi:function(){},clearCartApi:function(){},placeOrderApi:function(){},getUserApi:function(){},addCouponApi:function(){},removeCouponApi:function(){}};function i(t){o=e(e({},o),t)}function a(){r=new t({host:"http://boston.backbone-api.demo.aboutyou.cloud/v1/",auth:{username:"aboutyou",password:"OmNErAb96Y5Qn75SFhXr"},shopId:121})}var u=o.getProductApi,c=o.getCategoryApi,p=o.addToCartApi,s=o.removeFromCartApi,l=o.clearCartApi,f=o.placeOrderApi,h=o.getUserApi,d=o.addCouponApi,b=o.removeCouponApi;export{d as addCoupon,p as addToCart,r as api,l as clearCart,c as getCategory,u as getProduct,h as getUser,i as override,f as placeOrder,b as removeCoupon,s as removeFromCart,a as setup};
