language: node_js
node_js: "10"

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn

jobs:
  include:
    - stage: Build
      name: "Build"
      script:
        - yarn build:ct:tools

    - stage: test
      script: yarn test:ct:api-client
      name: "Test commercetools api-client"

    - stage: test
      script: yarn test:ct:composables
      name: "Test commercetools composables"

    - stage: test
      script: yarn test:ct:helpers
      name: "Test commercetools helpers"

