language: node_js

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn

jobs:
  include:
    - stage: Build
      name: "Build"
      script:
        - yarn build:ct:tools
      node_js: "10"

    - stage: test
      name: "Test commercetools api-client"
      node_js: "10"
      script: yarn test:ct:api-client
    - script: yarn test:ct:composables
      name: "Test commercetools composables"
    - script: yarn test:ct:helpers
      name: "Test commercetools helpers"

