<template>
<div>
  <h1>Overview [WIP]</h1>
  <p>Most of the modern eCommerce platforms is slow, heavy and complicated. We believe that there is no reason for it to be like that. Vue Storefront is a headless eCommerce frontend that can work with <b>any</b> backend platform. It can connect with your eCommerce platform, CMS, ERP, PIM or anything else via it's API. Because of that you can benefit from the flexibilility and speed of a modern Progressive Web Applications while still leveraging the services that you're already using!
  <h2>Architecture</h2>
  <p>
    Vue Storefront as a concept is embracing the modular approach to building eCommerce frontends.
    Essentialy the project itself is just a set of <b>independent</b> NPM packages providing different eCommerce/CMS/app functionalities that can be used in any combination. While building your Vue Storefront shop you're just picking the packages that you need for this specific project.
  </p>
  <p>
    The fact that Vue Storefront packages are standalone allows to use them in <b>any Vue.js enviroment</b> so you're not forced to use Nuxt. You can use Vue Storefront packages with Vue CLI or even within your custom Vue.js codebase.
  </p>
  <p> <!-- tip -->
    Even though the packages can be used as they are in any enviroment if you're using Vue Storefront to build fully-functional eCommerce app it is recommended to use Nuxt and theme generated by Vue Storefront CLI. Core packages were optimized to work best in this enviroment and we are offering some additional features with <code>@vue-storefront/nuxt</code> module.
    Also the CLI-generated boilerplate theme can significantly speed up your development!
  </p>
  <h2>Key features</h2>
  <ul>
    <li>Extremely fast</li>
    <li>Works with any backend, CMS, ERP, PIM and anything else that has API</li>
    <li>Server Side Rendering</li>
    <li>Progressive Web App</li>
    <li>Huge flexibility in changing third-party services</li>
  </ul>
  <h2>Technology stack</h2>
  <ul>
    <li>Vue.js</li>
    <li>Nuxt.js</li>
    <li>SCSS</li>
    <li>Storefront UI (optional)</li>
    <li>TypeScript (optional)</li>
  </ul>
</div>
</template>
