name: Lighthouse
on: [push]
jobs:
  lhci:
    name: Commercetools
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: yarn install, build
        run: |
          yarn
          yarn build:ct
      - name: run Lighthouse CI
        run: |
          yarn add @lhci/cli@0.3.x -W
          yarn lhci autorun --config=./lighthouserc.json || echo "LHCI failed!"
